[package]
name = "grr-imgui"
version = "0.1.0"
authors = ["msiglreith <m.siglreith@gmail.com>"]
edition = "2018"

[dependencies]
imgui = "0.2"
grr = "0.7"

[dev-dependencies]
glutin = "0.19"
imgui-winit-support = "0.2"
